import { HalkaArz } from '../types/portfolio';

export const CURRENT_HALKA_ARZLAR: HalkaArz[] = [
  {
    id: 'ipo-ntglb',
    companyName: 'Net Global Endüstriyel Yatırımlar A.Ş.',
    code: 'NTGLB',
    status: 'talep_toplaniyor',
    statusLabel: 'Talep Toplanıyor',
    dates: '9 - 11 Eylül 2026',
    price: 25.52,
    totalLots: 40000000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: true,
    market: 'Yıldız Pazar',
    availableInZiraat: true,
    ziraatNote: 'Ziraat Mobil ve Ziraat Yatırım üzerinden nakit veya fon blokajlı katılım var.',
    availableInMidas: true,
    midasNote: 'Midas ile Katılım Var: Borsa üzerinden hisse alır gibi talep girilebilir.',
    leadConsortium: 'A1 Capital Yatırım',
    isNew: true,
    estimatedLots: [
      { participants: '1.5 Milyon Kişi', lots: 27, totalCost: 689 },
      { participants: '2.0 Milyon Kişi', lots: 20, totalCost: 510 },
      { participants: '2.5 Milyon Kişi', lots: 16, totalCost: 408 },
      { participants: '3.0 Milyon Kişi', lots: 13, totalCost: 332 },
    ],
  },
  {
    id: 'ipo-1',
    companyName: 'Koç Metalurji A.Ş.',
    code: 'KOCMT',
    status: 'islem_goruyor',
    statusLabel: 'BIST İşlemde',
    dates: 'BIST Yıldız Pazar',
    price: 20.50,
    totalLots: 125000000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: true,
    market: 'Yıldız Pazar',
    availableInZiraat: true,
    ziraatNote: 'Halka arzı tamamlandı, Ziraat portföyünde serbest işlem görüyor.',
    availableInMidas: true,
    midasNote: 'Halka arzı tamamlandı, Midas üzerinden anlık alınıp satılabilir.',
    leadConsortium: 'İnfo Yatırım Menkul Değerler',
    isNew: false,
    estimatedLots: [
      { participants: '1.5 Milyon Kişi', lots: 58, totalCost: 1189 },
      { participants: '2.0 Milyon Kişi', lots: 44, totalCost: 902 },
      { participants: '2.5 Milyon Kişi', lots: 35, totalCost: 717 },
      { participants: '3.0 Milyon Kişi', lots: 29, totalCost: 594 },
    ],
  },
  {
    id: 'ipo-2',
    companyName: 'Durukan Şekerleme Sanayi',
    code: 'DURKN',
    status: 'islem_goruyor',
    statusLabel: 'BIST İşlemde',
    dates: 'BIST Ana Pazar',
    price: 17.00,
    totalLots: 42500000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: true,
    market: 'Ana Pazar',
    availableInZiraat: true,
    ziraatNote: 'Ziraat konsorsiyum üyesi olarak katılım sağlamıştı; şu an BIST Ana Pazar\'da işlem görüyor.',
    availableInMidas: false,
    midasNote: 'Konsorsiyum Dışı: Halka arzına Midas üzerinden katılınamamıştı; şu an hisse olarak serbest işlemde.',
    leadConsortium: 'Deniz Yatırım',
    isNew: false,
    estimatedLots: [
      { participants: '1.5 Milyon Kişi', lots: 22, totalCost: 374 },
      { participants: '2.0 Milyon Kişi', lots: 16, totalCost: 272 },
      { participants: '2.5 Milyon Kişi', lots: 13, totalCost: 221 },
      { participants: '3.0 Milyon Kişi', lots: 11, totalCost: 187 },
    ],
  },
  {
    id: 'ipo-3',
    companyName: 'Onur Yüksek Teknoloji A.Ş.',
    code: 'ONRYT',
    status: 'islem_goruyor',
    statusLabel: 'İşlem Görüyor',
    dates: 'Geçtiğimiz Hafta',
    price: 49.50,
    totalLots: 19730000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: true,
    market: 'Yıldız Pazar',
    availableInZiraat: true,
    ziraatNote: 'İşlem görüyor, Ziraat üzerinden serbestçe alınıp satılabilir.',
    availableInMidas: true,
    midasNote: 'İşlem görüyor, Midas üzerinden anlık alınıp satılabilir.',
    leadConsortium: 'Gedik Yatırım',
    tavanCount: 4,
    estimatedLots: [
      { participants: '2.0 Milyon Kişi', lots: 8, totalCost: 396 },
      { participants: '2.5 Milyon Kişi', lots: 6, totalCost: 297 },
      { participants: '3.0 Milyon Kişi', lots: 5, totalCost: 247 },
    ],
  },
  {
    id: 'ipo-4',
    companyName: 'Horoz Lojistik Kargo Hizmetleri',
    code: 'HOROZ',
    status: 'islem_goruyor',
    statusLabel: 'İşlem Görüyor',
    dates: 'Geçtiğimiz Hafta',
    price: 55.00,
    totalLots: 24600000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: false,
    market: 'Yıldız Pazar',
    availableInZiraat: true,
    ziraatNote: 'İşlem görüyor, Ziraat portföyünüzde takip edilebilir.',
    availableInMidas: true,
    midasNote: 'İşlem görüyor, Midas ile alınıp satılabilir.',
    leadConsortium: 'QNB Finansinvest',
    tavanCount: 2,
    estimatedLots: [
      { participants: '2.0 Milyon Kişi', lots: 10, totalCost: 550 },
      { participants: '2.5 Milyon Kişi', lots: 8, totalCost: 440 },
    ],
  },
  {
    id: 'ipo-5',
    companyName: 'Lila Kağıt Sanayi ve Ticaret',
    code: 'LILAK',
    status: 'tamamlandi',
    statusLabel: 'Tamamlandı',
    dates: 'Tamamlandı',
    price: 37.39,
    totalLots: 120000000,
    distributionType: 'Bireysele Eşit',
    katilimEndeksi: true,
    market: 'Yıldız Pazar',
    availableInZiraat: true,
    ziraatNote: 'Tamamlandı, BIST Yıldız Pazar\'da işlem görüyor.',
    availableInMidas: true,
    midasNote: 'Tamamlandı, Midas üzerinden serbest işlemde.',
    leadConsortium: 'Ak Yatırım / Yapı Kredi Yatırım',
    estimatedLots: [
      { participants: '2.5 Milyon Kişi', lots: 34, totalCost: 1271 },
      { participants: '3.0 Milyon Kişi', lots: 28, totalCost: 1046 },
    ],
  },
];

export async function fetchLatestHalkaArzlar(): Promise<HalkaArz[]> {
  // Simulates instant or online fetch of SPK approved IPOs
  return CURRENT_HALKA_ARZLAR;
}

export function getActiveIposCount(ipos: HalkaArz[]): number {
  return ipos.filter((i) => i.status === 'talep_toplaniyor').length;
}

export function getIpoByCode(code: string, ipos: HalkaArz[] = CURRENT_HALKA_ARZLAR): HalkaArz | undefined {
  return ipos.find((i) => i.code.toUpperCase() === code.trim().toUpperCase());
}
